/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JDesktopPane;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author VIctor
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpEscritorio = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        opcRegistrar = new javax.swing.JMenu();
        opcRegistrarPersona = new javax.swing.JMenuItem();
        opcRegistroEnvio = new javax.swing.JMenuItem();
        opcRegistroMercancia = new javax.swing.JMenuItem();
        opcRegistrarFactura = new javax.swing.JMenuItem();
        opcSalir = new javax.swing.JMenuItem();
        opcConsulta = new javax.swing.JMenu();
        opcConsultarPersona = new javax.swing.JMenuItem();
        opcConsultarEnvios = new javax.swing.JMenuItem();
        opcConsultarMercancia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpEscritorio.setBackground(new java.awt.Color(124, 124, 167));

        jLabel1.setFont(new java.awt.Font("Parchment", 1, 80)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Multinivel");
        jdpEscritorio.add(jLabel1);
        jLabel1.setBounds(150, 300, 250, 86);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Victor Julio Huertas Gómez");
        jdpEscritorio.add(jLabel2);
        jLabel2.setBounds(210, 370, 190, 19);

        menuBar.setBackground(new java.awt.Color(255, 255, 255));
        menuBar.setAlignmentY(0.5F);

        opcRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        opcRegistrar.setMnemonic('f');
        opcRegistrar.setText("Registrar");
        opcRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        opcRegistrarPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        opcRegistrarPersona.setBackground(new java.awt.Color(255, 255, 255));
        opcRegistrarPersona.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcRegistrarPersona.setMnemonic('a');
        opcRegistrarPersona.setText("Registrar Persona");
        opcRegistrarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRegistrarPersonaActionPerformed(evt);
            }
        });
        opcRegistrar.add(opcRegistrarPersona);

        opcRegistroEnvio.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        opcRegistroEnvio.setBackground(new java.awt.Color(255, 255, 255));
        opcRegistroEnvio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcRegistroEnvio.setMnemonic('o');
        opcRegistroEnvio.setText("Registrar Envio");
        opcRegistrar.add(opcRegistroEnvio);

        opcRegistroMercancia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        opcRegistroMercancia.setBackground(new java.awt.Color(255, 255, 255));
        opcRegistroMercancia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcRegistroMercancia.setMnemonic('s');
        opcRegistroMercancia.setText("Registrar Mercancia");
        opcRegistroMercancia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRegistroMercanciaActionPerformed(evt);
            }
        });
        opcRegistrar.add(opcRegistroMercancia);

        opcRegistrarFactura.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        opcRegistrarFactura.setBackground(new java.awt.Color(255, 255, 255));
        opcRegistrarFactura.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcRegistrarFactura.setMnemonic('a');
        opcRegistrarFactura.setText("Registrar Factura");
        opcRegistrarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcRegistrarFacturaActionPerformed(evt);
            }
        });
        opcRegistrar.add(opcRegistrarFactura);

        opcSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        opcSalir.setBackground(new java.awt.Color(255, 255, 255));
        opcSalir.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcSalir.setMnemonic('x');
        opcSalir.setText("Salir");
        opcSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcSalirActionPerformed(evt);
            }
        });
        opcRegistrar.add(opcSalir);

        menuBar.add(opcRegistrar);

        opcConsulta.setBackground(new java.awt.Color(255, 255, 255));
        opcConsulta.setMnemonic('e');
        opcConsulta.setText("Consultar");
        opcConsulta.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        opcConsultarPersona.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        opcConsultarPersona.setBackground(new java.awt.Color(255, 255, 255));
        opcConsultarPersona.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcConsultarPersona.setMnemonic('t');
        opcConsultarPersona.setText("Consltar Persona");
        opcConsulta.add(opcConsultarPersona);

        opcConsultarEnvios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        opcConsultarEnvios.setBackground(new java.awt.Color(255, 255, 255));
        opcConsultarEnvios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcConsultarEnvios.setMnemonic('p');
        opcConsultarEnvios.setText("Consultar Envios");
        opcConsulta.add(opcConsultarEnvios);

        opcConsultarMercancia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        opcConsultarMercancia.setBackground(new java.awt.Color(255, 255, 255));
        opcConsultarMercancia.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        opcConsultarMercancia.setMnemonic('y');
        opcConsultarMercancia.setText("Consultar Mercancia");
        opcConsulta.add(opcConsultarMercancia);

        menuBar.add(opcConsulta);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpEscritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opcSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_opcSalirActionPerformed

    private void opcRegistroMercanciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRegistroMercanciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcRegistroMercanciaActionPerformed

    private void opcRegistrarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRegistrarPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcRegistrarPersonaActionPerformed

    private void opcRegistrarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcRegistrarFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opcRegistrarFacturaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JDesktopPane jdpEscritorio;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu opcConsulta;
    private javax.swing.JMenuItem opcConsultarEnvios;
    private javax.swing.JMenuItem opcConsultarMercancia;
    private javax.swing.JMenuItem opcConsultarPersona;
    private javax.swing.JMenu opcRegistrar;
    private javax.swing.JMenuItem opcRegistrarFactura;
    private javax.swing.JMenuItem opcRegistrarPersona;
    private javax.swing.JMenuItem opcRegistroEnvio;
    private javax.swing.JMenuItem opcRegistroMercancia;
    private javax.swing.JMenuItem opcSalir;
    // End of variables declaration//GEN-END:variables

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JDesktopPane getJdpEscritorio() {
        return jdpEscritorio;
    }

    public void setJdpEscritorio(JDesktopPane jdpEscritorio) {
        this.jdpEscritorio = jdpEscritorio;
    }

    public void setMenuBar(JMenuBar menuBar) {
        this.menuBar = menuBar;
    }

    public JMenu getOpcConsulta() {
        return opcConsulta;
    }

    public void setOpcConsulta(JMenu opcConsulta) {
        this.opcConsulta = opcConsulta;
    }

    public JMenuItem getOpcConsultarEnvios() {
        return opcConsultarEnvios;
    }

    public void setOpcConsultarEnvios(JMenuItem opcConsultarEnvios) {
        this.opcConsultarEnvios = opcConsultarEnvios;
    }

    public JMenuItem getOpcConsultarMercancia() {
        return opcConsultarMercancia;
    }

    public void setOpcConsultarMercancia(JMenuItem opcConsultarMercancia) {
        this.opcConsultarMercancia = opcConsultarMercancia;
    }

    public JMenuItem getOpcConsultarPersona() {
        return opcConsultarPersona;
    }

    public void setOpcConsultarPersona(JMenuItem opcConsultarPersona) {
        this.opcConsultarPersona = opcConsultarPersona;
    }

    public JMenu getOpcRegistrar() {
        return opcRegistrar;
    }

    public void setOpcRegistrar(JMenu opcRegistrar) {
        this.opcRegistrar = opcRegistrar;
    }

    public JMenuItem getOpcRegistrarPersona() {
        return opcRegistrarPersona;
    }

    public void setOpcRegistrarPersona(JMenuItem opcRegistrarPersona) {
        this.opcRegistrarPersona = opcRegistrarPersona;
    }

    public JMenuItem getOpcRegistroEnvio() {
        return opcRegistroEnvio;
    }

    public void setOpcRegistroEnvio(JMenuItem opcRegistroEnvio) {
        this.opcRegistroEnvio = opcRegistroEnvio;
    }

    public JMenuItem getOpcRegistroMercancia() {
        return opcRegistroMercancia;
    }

    public void setOpcRegistroMercancia(JMenuItem opcRegistroMercancia) {
        this.opcRegistroMercancia = opcRegistroMercancia;
    }

    public JMenuItem getOpcSalir() {
        return opcSalir;
    }

    public void setOpcSalir(JMenuItem opcSalir) {
        this.opcSalir = opcSalir;
    }

    public JMenuItem getOpcRegistrarFactura() {
        return opcRegistrarFactura;
    }

    public void setOpcRegistrarFactura(JMenuItem opcRegistrarFactura) {
        this.opcRegistrarFactura = opcRegistrarFactura;
    }

    
}
